"""
Test GPTSniffer with ChatGPT-generated code samples
"""
import requests
import json

def test_code(code, description):
    """Test a code snippet and print results"""
    url = "http://localhost:8001/predict"
    payload = {"code": code}
    
    print("\n" + "=" * 80)
    print(f"TEST: {description}")
    print("=" * 80)
    print("Code:")
    print(code)
    print("-" * 80)
    
    try:
        response = requests.post(url, json=payload)
        
        if response.status_code == 200:
            result = response.json()
            print(f"Prediction: {result['label']}")
            print(f"Confidence: {result['confidence']:.4f} ({result['confidence']*100:.2f}%)")
            print(f"Probabilities:")
            print(f"  ChatGPT: {result['probabilities']['ChatGPT']:.4f} ({result['probabilities']['ChatGPT']*100:.2f}%)")
            print(f"  Human:   {result['probabilities']['Human']:.4f} ({result['probabilities']['Human']*100:.2f}%)")
            
            # Determine if prediction is correct
            is_correct = result['label'] == 'ChatGPT'
            status = "✅ CORRECT" if is_correct else "❌ WRONG - Should be ChatGPT!"
            print(f"\nResult: {status}")
            return is_correct
        else:
            print(f"Error: {response.status_code}")
            print(response.text)
            return False
    except Exception as e:
        print(f"Exception: {e}")
        return False

# Test samples - All generated by ChatGPT
test_samples = [
    {
        "description": "ChatGPT Code #1 - Binary Search",
        "code": """def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    
    while left <= right:
        mid = (left + right) // 2
        
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    
    return -1

# Example usage
arr = [1, 3, 5, 7, 9, 11, 13, 15]
target = 7
result = binary_search(arr, target)
print(f"Target {target} found at index: {result}")"""
    },
    {
        "description": "ChatGPT Code #2 - Palindrome Checker",
        "code": """def is_palindrome(s):
    # Remove spaces and convert to lowercase
    s = s.replace(" ", "").lower()
    
    # Check if string is equal to its reverse
    return s == s[::-1]

# Test cases
test_strings = ["racecar", "hello", "A man a plan a canal Panama"]
for string in test_strings:
    result = is_palindrome(string)
    print(f"'{string}' is palindrome: {result}")"""
    },
    {
        "description": "ChatGPT Code #3 - Factorial Calculator",
        "code": """def factorial(n):
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

# Calculate factorials
for i in range(6):
    print(f"{i}! = {factorial(i)}")"""
    },
    {
        "description": "ChatGPT Code #4 - Quick Sort",
        "code": """def quicksort(arr):
    if len(arr) <= 1:
        return arr
    
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    
    return quicksort(left) + middle + quicksort(right)

# Test
numbers = [3, 6, 8, 10, 1, 2, 1]
sorted_numbers = quicksort(numbers)
print(f"Original: {numbers}")
print(f"Sorted: {sorted_numbers}")"""
    },
    {
        "description": "ChatGPT Code #5 - Prime Number Checker",
        "code": """def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find first 10 prime numbers
primes = []
num = 2
while len(primes) < 10:
    if is_prime(num):
        primes.append(num)
    num += 1

print("First 10 prime numbers:", primes)"""
    },
    {
        "description": "ChatGPT Code #6 - Class with Methods",
        "code": """class Calculator:
    def __init__(self):
        self.result = 0
    
    def add(self, x):
        self.result += x
        return self
    
    def subtract(self, x):
        self.result -= x
        return self
    
    def multiply(self, x):
        self.result *= x
        return self
    
    def get_result(self):
        return self.result

# Usage
calc = Calculator()
result = calc.add(10).multiply(5).subtract(3).get_result()
print(f"Result: {result}")"""
    },
    {
        "description": "ChatGPT Code #7 - Merge Two Sorted Lists",
        "code": """def merge_sorted_lists(list1, list2):
    merged = []
    i, j = 0, 0
    
    while i < len(list1) and j < len(list2):
        if list1[i] <= list2[j]:
            merged.append(list1[i])
            i += 1
        else:
            merged.append(list2[j])
            j += 1
    
    merged.extend(list1[i:])
    merged.extend(list2[j:])
    
    return merged

# Test
list1 = [1, 3, 5, 7]
list2 = [2, 4, 6, 8]
print(merge_sorted_lists(list1, list2))"""
    },
    {
        "description": "ChatGPT Code #8 - FizzBuzz",
        "code": """def fizzbuzz(n):
    for i in range(1, n + 1):
        if i % 15 == 0:
            print("FizzBuzz")
        elif i % 3 == 0:
            print("Fizz")
        elif i % 5 == 0:
            print("Buzz")
        else:
            print(i)

# Run FizzBuzz for 1 to 20
fizzbuzz(20)"""
    }
]

print("\n" + "=" * 80)
print("TESTING GPTSniffer WITH CHATGPT-GENERATED CODE")
print("All samples below are generated by ChatGPT")
print("Expected: Model should detect them as 'ChatGPT'")
print("=" * 80)

# Run all tests
results = []
for sample in test_samples:
    result = test_code(sample["code"], sample["description"])
    results.append({
        "description": sample["description"],
        "correct": result
    })

# Summary
print("\n" + "=" * 80)
print("SUMMARY")
print("=" * 80)

correct_count = sum(1 for r in results if r["correct"])
total_count = len(results)
accuracy = (correct_count / total_count) * 100

for i, result in enumerate(results, 1):
    status = "✅" if result["correct"] else "❌"
    print(f"{status} Test {i}: {result['description']}")

print("-" * 80)
print(f"Total: {correct_count}/{total_count} correct")
print(f"Accuracy: {accuracy:.2f}%")

if accuracy < 50:
    print("\n⚠️ WARNING: Model is performing poorly on ChatGPT code!")
    print("This might indicate:")
    print("  1. Model needs more training epochs")
    print("  2. Training data might be mislabeled")
    print("  3. Code style doesn't match training data patterns")
elif accuracy < 80:
    print("\n⚠️ Model accuracy is below expected (should be >85%)")
else:
    print("\n✅ Model is performing well!")
